apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: role-all-ns-reader
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-k8s-dev-ns-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-all-ns-reader
subjects:
- kind: User
  name: k8s-dev